# Generated by Django 4.1.3 on 2023-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
