# Generated by Django 4.2 on 2023-05-21 19:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('sidebar', ckeditor.fields.RichTextField(verbose_name='Sidebar')),
                ('headtext1', models.TextField(blank=True, null=True, verbose_name='Head Text 1')),
                ('headtext2', models.TextField(blank=True, null=True, verbose_name='Head Text 2')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Site Logo')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Configs',
            },
        ),
        migrations.CreateModel(
            name='vpnlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='VPN Title')),
                ('day', models.IntegerField(verbose_name='Active Day')),
                ('price_t', models.CharField(max_length=150, verbose_name='Price Toman')),
                ('price_c', models.CharField(blank=True, max_length=150, null=True, verbose_name='Price Digital currency')),
                ('row', models.IntegerField(verbose_name='Row')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'vpnlist',
                'verbose_name_plural': 'vpnlists',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buydate', models.DateTimeField(auto_now_add=True, verbose_name='Buy Date')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('refid', models.CharField(max_length=200, verbose_name='Ref ID')),
                ('authority', models.CharField(max_length=200, verbose_name='Authority')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vpn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn.vpnlist', verbose_name='VPN')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
