# Generated by Django 4.2 on 2023-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vpnlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='VPN Title')),
                ('day', models.IntegerField(verbose_name='Active Day')),
                ('price_t', models.CharField(max_length=150, verbose_name='Price Toman')),
                ('price_c', models.CharField(max_length=150, verbose_name='Price Digital currency')),
                ('row', models.IntegerField(verbose_name='Row')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'vpnlist',
                'verbose_name_plural': 'vpnlists',
            },
        ),
    ]
