# Generated by Django 4.2.1 on 2023-06-06 06:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('sidebar', ckeditor.fields.RichTextField(verbose_name='Sidebar')),
                ('headtext1', models.TextField(blank=True, null=True, verbose_name='Head Text 1')),
                ('headtext2', models.TextField(blank=True, null=True, verbose_name='Head Text 2')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Site Logo')),
                ('buynote', models.TextField(blank=True, null=True, verbose_name='Buy Note')),
                ('chtelegram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Channel Telegram')),
                ('ig', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instagram')),
                ('telegram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Configs',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('Read', 'Read'), ('UnRead', 'UnRead')], default='UnRead', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='help', verbose_name='Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='dl', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Help',
                'verbose_name_plural': 'Helps',
            },
        ),
        migrations.CreateModel(
            name='vpnlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='VPN Title')),
                ('day', models.IntegerField(verbose_name='Active Day')),
                ('price_t', models.CharField(max_length=150, verbose_name='Price Toman')),
                ('price_c', models.CharField(blank=True, max_length=150, null=True, verbose_name='Price Digital currency')),
                ('row', models.IntegerField(verbose_name='Row')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'vpnlist',
                'verbose_name_plural': 'vpnlists',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buydate', models.DateTimeField(auto_now_add=True, verbose_name='Buy Date')),
                ('status', models.BooleanField(default=1, verbose_name='Status')),
                ('refid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ref ID')),
                ('authority', models.CharField(blank=True, max_length=200, null=True, verbose_name='Authority')),
                ('linkvpn', models.TextField(blank=True, null=True, verbose_name='Link')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vpn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn.vpnlist', verbose_name='VPN')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
