# Generated by Django 4.2.1 on 2023-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fileconfig',
            field=models.FileField(blank=True, null=True, upload_to='fileconfig', verbose_name='File Config'),
        ),
    ]
