# Generated by Django 4.1.3 on 2023-05-14 08:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Sidebars',
            },
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='price_c',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Price Digital currency'),
        ),
    ]
