# Generated by Django 4.2.1 on 2023-06-08 04:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_order_fileconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
    ]
