# Generated by Django 4.2 on 2023-05-20 17:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_sidebar_alter_vpnlist_price_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
    ]
