# Generated by Django 4.1.3 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='helpfile'),
        ),
        migrations.AddField(
            model_name='help',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='help', verbose_name='Image'),
        ),
    ]
