# Generated by Django 4.1.3 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_help_file_help_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dl', verbose_name='File'),
        ),
    ]
