# Generated by Django 4.1.3 on 2023-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_alter_help_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('Read', 'Read'), ('UnRead', 'UnRead')], default='UnRead', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
    ]
