# Generated by Django 4.2 on 2023-05-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='headtext1',
            field=models.TextField(blank=True, null=True, verbose_name='Head Text 1'),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='headtext2',
            field=models.TextField(blank=True, null=True, verbose_name='Head Text 2'),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo'),
        ),
    ]
