# Generated by Django 4.1.3 on 2023-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='buynote',
            field=models.TextField(blank=True, null=True, verbose_name='Buy Note'),
        ),
    ]
