# Generated by Django 4.1.3 on 2023-05-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_conf_buynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='chtelegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Channerl Telegram'),
        ),
        migrations.AddField(
            model_name='conf',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='conf',
            name='ig',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='conf',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram'),
        ),
    ]
