# Generated by Django 4.1.3 on 2023-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_conf_chtelegram_conf_email_conf_ig_conf_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='linkvpn',
            field=models.TextField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Authority'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ref ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Status'),
        ),
    ]
